language: ruby
# If you don't specify a version, Travis CI will use MRI 1.9.3 as the default.
# http://docs.travis-ci.com/user/languages/ruby/
rvm:
  - 2.6.1
services:
  - mongodb
  - elasticsearch
sudo: false
addons:
  firefox: "66.0"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
